services:
  db:
    image: mysql:8.4
    container_name: matcha-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: matcha_shop
    ports:
      - "3306:3306"
    volumes:
      - matcha_mysql_data:/var/lib/mysql

volumes:
  matcha_mysql_data:
